const statesCitiesData = [{
  state: "Andhra Pradesh", 
  cities: [
      'Adoni',
      'Amaravati',
      'Anantapur',
      'Chandragiri',
      'Chittoor',
      'Dowlaiswaram',
      'Eluru',
      'Guntur',
      'Kadapa',
      'Kakinada',
      'Kurnool',
      'Machilipatnam',
      'Nagarjunakoṇḍa',
      'Rajahmundry',
      'Srikakulam',
      'Tirupati',
      'Vijayawada',
      'Visakhapatnam',
      'Vizianagaram',
      'Yemmiganur'
  ]}, {
  state:'Arunachal Pradesh', 
  cities: [
      'Itanagar'
  ]}, {
  state:'Assam', 
  cities: [
      'Dhuburi',
      'Dibrugarh',
      'Dispur',
      'Guwahati',
      'Jorhat',
      'Nagaon',
      'Sibsagar',
      'Silchar',
      'Tezpur',
      'Tinsukia',
  ]}, {
  state:'Bihar', 
  cities: [
      'Ara',
      'Baruni',
      'Begusarai',
      'Bettiah',
      'Bhagalpur',
      'Bihar Sharif',
      'Bodh Gaya',
      'Buxar',
      'Chapra',
      'Darbhanga',
      'Dehri',
      'Dinapur Nizamat',
      'Gaya',
      'Hajipur',
      'Jamalpur',
      'Katihar',
      'Madhubani',
      'Motihari',
      'Munger',
      'Muzaffarpur',
      'Patna',
      'Purnia',
      'Pusa',
      'Saharsa',
      'Samastipur',
      'Sasaram',
      'Sitamarhi',
      'Siwan',
  ]}, {
  state:'Chandigarh', 
  cities: [
      'Chandigarh'
  ]}, {
  state:'Chhattisgarh', 
  cities: [
      'Ambikapur',
      'Bhilai',
      'Bilaspur',
      'Dhamtari',
      'Durg',
      'Jagdalpur',
      'Raipur',
      'Rajnandgaon',
  ]}, {
  state:'Dadra And Nagar Haveli (Union Territory)', 
  cities: [
      'Silvassa'
  ]}, {
  state:'Daman And Diu (Union Territory)', 
  cities: [
      'Daman',
      'Diu',
  ]}, {
  state:'Delhi (National Capital Territory)', 
  cities: [
      'Old Delhi',
      'New Delhi',
  ]}, {
  state:'Goa', 
  cities: [
      'Madgaon',
      'Panaji'
  ]}, {
  state:'Gujarat', 
  cities: [
      'Ahmadabad',
      'Amreli',
      'Bharuch',
      'Bhavnagar',
      'Bhuj',
      'Dwarka',
      'Gandhinagar',
      'Godhra',
      'Jamnagar',
      'Junagadh',
      'Kandla',
      'Khambhat',
      'Kheda',
      'Mahesana',
      'Morvi',
      'Nadiad',
      'Navsari',
      'Okha',
      'Palanpur',
      'Patan',
      'Porbandar',
      'Rajkot',
      'Surat',
      'Surendranagar',
      'Valsad',
      'Veraval',
  ]}, {
  state:'Haryana', 
  cities: [
      'Ambala',
      'Bhiwani',
      'Chandigarh',
      'Faridabad',
      'Firozpur Jhirka',
      'Gurgaon',
      'Hansi',
      'Hisar',
      'Jind',
      'Kaithal',
      'Karnal',
      'Kurukshetra',
      'Panipat',
      'Pehowa',
      'Rewari',
      'Rohtak',
      'Sirsa',
      'Sonipat',
  ]}, {
  state:'Himachal Pradesh', 
  cities: [
      'Bilaspur',
      'Chamba',
      'Dalhousie',
      'Dharmshala',
      'Hamirpur',
      'Kangra',
      'Kullu',
      'Mandi',
      'Nahan',
      'Shimla',
      'Una',
  ]}, {
  state:'Jammu And Kashmir (Union Territory)', 
  cities: [
      'Anantnag',
      'Baramula',
      'Doda',
      'Gulmarg',
      'Jammu',
      'Kathua',
      'Punch',
      'Rajauri',
      'Srinagar',
      'Udhampur',
  ]}, {
  state:'Jharkhand', 
  cities: [
      'Bokaro',
      'Chaibasa',
      'Deoghar',
      'Dhanbad',
      'Dumka',
      'Giridih',
      'Hazaribag',
      'Jamshedpur',
      'Jharia',
      'Rajmahal',
      'Ranchi',
      'Saraikela',
  ]}, {
  state:'Karnataka', 
  cities: [
      'Badami',
      'Ballari',
      'Bangalore',
      'Belgavi',
      'Bhadravati',
      'Bidar',
      'Chikkamagaluru',
      'Chitradurga',
      'Davangere',
      'Halebid',
      'Hassan',
      'Hubballi-Dharwad',
      'Kalaburagi',
      'Kolar',
      'Madikeri',
      'Mandya',
      'Mangaluru',
      'Mysuru',
      'Raichur',
      'Shivamogga',
      'Shravanabelagola',
      'Shrirangapattana',
      'Tumkuru',
  ]}, {
  state:'Kerala', 
  cities: [
      'Alappuzha',
      'Badagara',
      'Idukki',
      'Kannur',
      'Kochi',
      'Kollam',
      'Kottayam',
      'Kozhikode',
      'Mattancheri',
      'Palakkad',
      'Thalassery',
      'Thiruvananthapuram',
      'Thrissur',
  ]}, {
  state:'Ladakh', 
  cities: [
      'Kargil',
      'Leh',
  ]}, {
  state:'Madhya Pradesh', 
  cities: [
      'Balaghat',
      'Barwani',
      'Betul',
      'Bharhut',
      'Bhind',
      'Bhojpur',
      'Bhopal',
      'Burhanpur',
      'Chhatarpur',
      'Chhindwara',
      'Damoh',
      'Datia',
      'Dewas',
      'Dhar',
      'Guna',
      'Gwalior',
      'Hoshangabad',
      'Indore',
      'Itarsi',
      'Jabalpur',
      'Jhabua',
      'Khajuraho',
      'Khandwa',
      'Khargon',
      'Maheshwar',
      'Mandla',
      'Mandsaur',
      'Mhow',
      'Morena',
      'Murwara',
      'Narsimhapur',
      'Narsinghgarh',
      'Narwar',
      'Neemuch',
      'Nowgong',
      'Orchha',
      'Panna',
      'Raisen',
      'Rajgarh',
      'Ratlam',
      'Rewa',
      'Sagar',
      'Sarangpur',
      'Satna',
      'Sehore',
      'Seoni',
      'Shahdol',
      'Shajapur',
      'Sheopur',
      'Shivpuri',
      'Ujjain',
      'Vidisha',
  ]}, {
  state:'Maharashtra', 
  cities: [
      'Ahmadnagar',
      'Akola',
      'Amravati',
      'Aurangabad',
      'Bhandara',
      'Bhusawal',
      'Bid',
      'Buldana',
      'Chandrapur',
      'Daulatabad',
      'Dhule',
      'Jalgaon',
      'Kalyan',
      'Karli',
      'Kolhapur',
      'Mahabaleshwar',
      'Malegaon',
      'Matheran',
      'Mumbai',
      'Nagpur',
      'Nanded',
      'Nashik',
      'Osmanabad',
      'Pandharpur',
      'Parbhani',
      'Pune',
      'Ratnagiri',
      'Sangli',
      'Satara',
      'Sevagram',
      'Solapur',
      'Thane',
      'Ulhasnagar',
      'Vasai-Virar',
      'Wardha',
      'Yavatmal',
  ]}, {
  state:'Manipur', 
  cities: [
      'Imphal'
  ]}, {
  state:'Meghalaya', 
  cities: [
      'Cherrapunji',
      'Shillong',
      'Mizoram',
      'Aizawl',
      'Lunglei',
  ]}, {
  state:'Nagaland', 
  cities: [
      'Kohima',
      'Mon',
      'Phek',
      'Wokha',
      'Zunheboto'
  ]}, {
  state:'Odisha', 
  cities: [
      'Balangir',
      'Baleshwar',
      'Baripada',
      'Bhubaneshwar',
      'Brahmapur',
      'Cuttack',
      'Dhenkanal',
      'Keonjhar',
      'Konark',
      'Koraput',
      'Paradip',
      'Phulabani',
      'Puri',
      'Sambalpur',
      'Udayagiri',
  ]}, {
  state:'Pondicherry', 
  cities: [
      'Karaikal',
      'Mahe',
      'Pondicherry',
      'Yanam',
  ]}, {
  state:'Punjab', 
  cities: [
      'Amritsar',
      'Batala',
      'Chandigarh',
      'Faridkot',
      'Firozpur',
      'Gurdaspur',
      'Hoshiarpur',
      'Jalandhar',
      'Kapurthala',
      'Ludhiana',
      'Nabha',
      'Patiala',
      'Rupnagar',
      'Sangrur',
  ]}, {
  state:'Rajasthan', 
  cities: [
      'Abu',
      'Ajmer',
      'Alwar',
      'Amer',
      'Barmer',
      'Beawar',
      'Bharatpur',
      'Bhilwara',
      'Bikaner',
      'Bundi',
      'Chittaurgarh',
      'Churu',
      'Dhaulpur',
      'Dungarpur',
      'Ganganagar',
      'Hanumangarh',
      'Jaipur',
      'Jaisalmer',
      'Jalor',
      'Jhalawar',
      'Jhunjhunu',
      'Jodhpur',
      'Kishangarh',
      'Kota',
      'Merta',
      'Nagaur',
      'Nathdwara',
      'Pali',
      'Phalodi',
      'Pushkar',
      'Sawai Madhopur',
      'Shahpura',
      'Sikar',
      'Sirohi',
      'Tonk',
      'Udaipur',
  ]}, {
  state:'Sikkim', 
  cities: [
      'Gangtok',
      'Gyalsing',
      'Lachung',
      'Mangan',
  ]}, {
  state:'Tamil Nadu', 
  cities: [
      'Arcot',
      'Chengalpattu',
      'Chennai',
      'Chidambaram',
      'Coimbatore',
      'Cuddalore',
      'Dharmapuri',
      'Dindigul',
      'Erode',
      'Kanchipuram',
      'Kanniyakumari',
      'Kodaikanal',
      'Kumbakonam',
      'Madurai',
      'Mamallapuram',
      'Nagappattinam',
      'Nagercoil',
      'Palayankottai',
      'Pudukkottai',
      'Rajapalaiyam',
      'Ramanathapuram',
      'Salem',
      'Thanjavur',
      'Tiruchchirappalli',
      'Tirunelveli',
      'Tiruppur',
      'Tuticorin',
      'Udhagamandalam',
      'Vellore',
  ]}, {
  state:'Telangana', 
  cities: [
      'Hyderabad',
      'Karimnagar',
      'Khammam',
      'Mahbubnagar',
      'Nizamabad',
      'Sangareddi',
      'Warangal',
  ]}, {
  state:'Tripura', 
  cities: [
      'Agartala',
  ]}, {
  state:'Uttar Pradesh', 
  cities: [
      'Agra',
      'Aligarh',
      'Amroha',
      'Ayodhya',
      'Azamgarh',
      'Bahraich',
      'Ballia',
      'Banda',
      'Bara Banki',
      'Bareilly',
      'Basti',
      'Bijnor',
      'Bithur',
      'Budaun',
      'Bulandshahr',
      'Deoria',
      'Etah',
      'Etawah',
      'Faizabad',
      'Farrukhabad-cum-Fatehgarh',
      'Fatehpur',
      'Fatehpur Sikri',
      'Ghaziabad',
      'Ghazipur',
      'Gonda',
      'Gorakhpur',
      'Hamirpur',
      'Hardoi',
      'Hathras',
      'Jalaun',
      'Jaunpur',
      'Jhansi',
      'Kannauj',
      'Kanpur',
      'Lakhimpur',
      'Lalitpur',
      'Lucknow',
      'Mainpuri',
      'Mathura',
      'Meerut',
      'Mirzapur-Vindhyachal',
      'Moradabad',
      'Muzaffarnagar',
      'Partapgarh',
      'Pilibhit',
      'Prayagraj',
      'Rae Bareli',
      'Rampur',
      'Saharanpur',
      'Sambhal',
      'Shahjahanpur',
      'Sitapur',
      'Sultanpur',
      'Tehri',
      'Varanasi',
  ]}, {
  state:'Uttarakhand', 
  cities: [
      'Almora',
      'Dehra Dun',
      'Haridwar',
      'Mussoorie',
      'Nainital',
      'Pithoragarh',
  ]}, {
  state:'West Bengal', 
  cities: [
      'Alipore',
      'Alipur Duar',
      'Asansol',
      'Baharampur',
      'Bally',
      'Balurghat',
      'Bankura',
      'Baranagar',
      'Barasat',
      'Barrackpore',
      'Basirhat',
      'Bhatpara',
      'Bishnupur',
      'Budge Budge',
      'Burdwan',
      'Chandernagore',
      'Darjiling',
      'Diamond Harbour',
      'Dum Dum',
      'Durgapur',
      'Halisahar',
      'Haora',
      'Hugli',
      'Ingraj Bazar',
      'Jalpaiguri',
      'Kalimpong',
      'Kamarhati',
      'Kanchrapara',
      'Kharagpur',
      'Koch Kolkata',
      'Krishnanagar',
      'Malda',
      'Midnapore',
      'Murshidabad',
      'Navadwip',
      'Palashi',
      'Panihati',
      'Purulia',
      'Raiganj',
      'Santipur',
      'Shantiniketan',
      'Shrirampur',
      'Siliguri',
      'Siuri',
      'Tamluk',
      'Titagarh',
  ]}
];

export default statesCitiesData;
